In [1]:
"""
날짜 : 2020/08/10
이름 : 유효진
내용 : Numpy(수치해석 패키지) 실습하기
"""

'\n날짜 : 2020/08/10\n이름 : 유효진\n내용 : Numpy(수치해석 패키지) 실습하기\n'

In [3]:
import numpy as np

In [6]:
# 벡터생성
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [8]:
v2 = np.arange(5)
v2

array([0, 1, 2, 3, 4])

In [10]:
# 0 ~ 1 사이의 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.48058948, 0.73098716, 0.54419808, 0.66507065, 0.3387793 ,
       0.63641666, 0.68430592, 0.44149358, 0.1761691 , 0.17811825,
       0.77076452, 0.28754177, 0.41621982, 0.52681834, 0.20428841,
       0.58805375, 0.51540945, 0.93766624, 0.79688777, 0.26165154,
       0.83043202, 0.34912999, 0.52630545, 0.15690182, 0.27126651,
       0.19774039, 0.79742135, 0.22631689, 0.76865936, 0.93628965,
       0.39330232, 0.26682707, 0.38323152, 0.5971777 , 0.71270386,
       0.70853847, 0.3591299 , 0.5805848 , 0.94730439, 0.28967687,
       0.34179338, 0.42092097, 0.94116168, 0.94508271, 0.43964404,
       0.78376453, 0.98970904, 0.7326675 , 0.23523235, 0.19468083,
       0.81165589, 0.57736812, 0.12338467, 0.08685371, 0.29911578,
       0.5724025 , 0.81948491, 0.02840314, 0.92500818, 0.0542017 ,
       0.9873174 , 0.65511866, 0.98333883, 0.80444117, 0.12476529,
       0.99182012, 0.18195669, 0.14296424, 0.76847053, 0.1262225 ,
       0.1723086 , 0.301264  , 0.49575937, 0.48125187, 0.37672

In [12]:
# 표준정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-1.15810473, -2.02115527,  0.40164213, -0.38281984,  0.21674649,
       -0.23192581,  1.80106204, -0.18810976, -0.01496741, -1.20262463,
       -1.06288411, -0.07147609, -0.68949164,  1.20536977, -0.69695945,
        0.02051841, -0.52038509,  0.52991269,  0.7850833 ,  0.45173905,
        0.69285734, -0.23660342, -1.45373759, -0.48535737, -1.42692577,
       -0.25589868,  1.50186533, -0.7352767 ,  0.58233353,  0.23153742,
       -0.52652367,  0.26971306, -0.1816474 ,  1.01679009, -0.71091177,
       -0.62335667, -1.18102894, -1.41662562,  0.36113682, -0.27344467,
       -0.72847374,  0.31100979, -0.44719593, -1.44952565, -0.07087759,
        0.28589827,  1.44671032,  0.12328864,  1.54471595, -0.06166627,
        0.13723635, -0.47585732, -0.08404299,  1.4468782 ,  2.06899005,
        0.45863076, -0.53117695, -1.24729676,  0.76422903,  0.64644105,
        1.4328675 , -1.24620353,  1.05229532, -0.29186152,  0.32685566,
       -0.52823835,  1.69392621,  0.92099365,  0.99101015, -0.76

In [13]:
# 평균 0, 표준편차 1인 정규분포를 따르는 임의의 실수 100개
rand3 = np.random.normal(0, 1, 100)
rand3

array([-8.95411000e-01,  2.12306455e+00,  1.36737358e+00,  1.57990257e+00,
        5.44179379e-01,  7.89878532e-04, -1.73425698e+00,  1.47671064e-02,
       -1.79813723e-02,  8.98550227e-01,  2.46321965e+00, -1.08694695e+00,
        8.00699600e-01,  4.41399656e-01,  4.13731696e-01,  1.15840592e+00,
       -6.90228158e-02, -1.67358396e+00, -5.98008619e-01, -2.11422828e+00,
        4.79590390e-01,  1.25086131e+00,  1.07205821e-01, -1.45372272e+00,
        1.69311736e+00,  9.37836020e-01,  8.10040991e-01,  6.50624142e-01,
        5.95948329e-01, -2.27322837e-01, -5.56247701e-01,  7.65064284e-01,
       -1.60394969e-02,  7.08152890e-02, -4.28093420e-01,  9.70994482e-01,
        2.36789459e+00,  5.18514103e-01,  1.44445200e+00, -1.44313690e+00,
       -5.69812714e-01,  9.94828874e-01,  1.08580137e+00, -9.58716697e-01,
        5.56453596e-02, -1.39942115e+00,  6.37237951e-02, -3.01892992e-01,
       -7.58930803e-01,  9.01861889e-01,  1.38592486e+00,  5.55423209e-01,
        7.18899116e-03,  